# Begin ~/.bash_profile
# User dependent .bash_profile file; executed by bash(1) for login shells.

# Guard
if ! [ $HOME_BASH_PROFILE ]; then
export HOME_BASH_PROFILE=1

# Ensure the system profile is sourced (for some reason it isn't sometimes)
source /etc/profile
echo "sourced /etc/profile"

# Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/bin" ] ; then
  pathprepend   ${HOME}/bin     PATH
  echo "${HOME}/bin prepended to PATH"
fi

###
## Additional, specific-type sources
###
# source the user's bash_envar if it exists
if [ -f "${HOME}/.config/bash/bash_envar" ] ; then
  source "${HOME}/.config/bash/bash_envar"
  echo "sourced ${HOME}/.config/bash/bash_envar"
fi

# source the user's bash_function if it exists
if [ -f "${HOME}/.config/bash/bash_function" ] ; then
  source "${HOME}/.config/bash/bash_function"
  echo "sourced ${HOME}/.config/bash/bash_function"
fi

# Set MANPATH so it includes users' private man if it exists
if [ -d "${HOME}/.config/bash/man" ]; then
  MANPATH="${HOME}/.config/bash/man:${MANPATH}"
fi

# Set INFOPATH so it includes users' private info if it exists
if [ -d "${HOME}/.config/bash/info" ]; then
  INFOPATH="${HOME}/.config/bash/info:${INFOPATH}"
fi

fi # End guard
# End ~/.bash_profile
