#
# Begin /etc/bash.bash_logout
# System-wide bash_logout file; executed by bash(1) when login shell exits.
#

# when leaving the console clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
  [ -x /usr/bin/clear ] && /usr/bin/clear
fi

# End /etc/bash_logout
