#!/bin/sh -e
#
# startkde-wrapper
# A wrapper for the startkde script, which launches kde/plasma

source setkf5
source /etc/profile
# This is now unnecessary
#source /etc/profile.d/kf5.sh

exec $KF5_PREFIX/bin/startkde "$@"

